
<img src="img/viu_logo.png" width="200">

## 04EPPY - Ciencia de Datos e Inteligencia Artificial
### NumPy

![logo](img/python_logo.png)

*Òscar Garibo*

# Sumario
- ndarray
- creacion y modificacion de ndarrays
- indexacion y slicing
- estadistica descriptiva
- filtrado de datos con where
- algebra lineal
- Valores aleatorios
- Leer y escribir NumPy ndarrays

# NumPy ndarray
- NumPy (__Num__ erical __Py__ thon) es la de facto librería estándar para análisis numérico en Python
- Estructura de datos multidimensional eficiente (escrita en C): ndarray
- Colección de funciones para álgebra lineal, estadística descriptiva
- Ayuda al procesamiento de datos (np.where)

In [1]:
#importar libreria
import numpy as np

In [4]:
array = np.array([[2,71,0,34], [2,171,-35,34]])
print(array)

[[  2  71   0  34]
 [  2 171 -35  34]]


In [4]:
type(array)

numpy.ndarray

In [3]:
array.argmin()

6

In [7]:
array.argmax()

5

In [8]:
array.nonzero()

(array([0, 0, 0, 1, 1, 1, 1], dtype=int64),
 array([0, 1, 3, 0, 1, 2, 3], dtype=int64))

In [9]:
array[1].nonzero()

(array([0, 1, 2, 3], dtype=int64),)

In [ ]:
!pip install numpy

In [10]:
shopping_list = [ ['onions','carrots','celery'], ['apples','oranges','grapes'] ] # 2D
array = np.array(shopping_list) # convertir una lista en una ndarray
print(array)
print(type(array))

[['onions' 'carrots' 'celery']
 ['apples' 'oranges' 'grapes']]
<class 'numpy.ndarray'>


## Formas de crear ndarrays

In [11]:
range(2)

range(0, 2)

In [12]:
print(np.array([100,10,1])) # array a partir de una lista
print(np.arange(2,10,2))    # array a partir de una secuencia(range) 1D

[100  10   1]
[2 4 6 8]


In [13]:
print(np.zeros(2))       # 1D

[0. 0.]


In [9]:
print(np.ones((2,2))) # matrix 2x2
print(np.ones((2,3)))

[[1. 1.]
 [1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
print(np.empty((2,2,2))) # matrix 2x2x2, no inicializados

[[[4.67296746e-307 1.69121096e-306]
  [1.86921822e-306 1.37961709e-306]]

 [[1.42419938e-306 7.56603881e-307]
  [8.45603440e-307 4.45046008e-307]]]


In [16]:
cosa = np.array([[2,71,0,34], [2,171,-35,34]])

In [17]:
cosa

array([[  2,  71,   0,  34],
       [  2, 171, -35,  34]])

In [18]:
print(np.full((5,2),3)) # matrix 5x2

[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]


In [19]:
print(np.eye(3))         # matrix identity

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
# Generar arrays con valores fijos
print(np.zeros(2))       # 1D
print(np.ones((2,2)))    # matrix 2x2
print(np.empty((2,2,2))) # matrix 2x2x2, no inicializados
print(np.full((5,2),3)) # matrix 5x2
print(np.eye(3))         # matrix identity

[0. 0.]
[[1. 1.]
 [1. 1.]]
[[[4.67296746e-307 1.69121096e-306]
  [1.86921822e-306 1.37961709e-306]]

 [[1.42419938e-306 7.56603881e-307]
  [8.45603440e-307 4.45046008e-307]]]
[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Obtener información sobre ndarray

In [21]:
my_ndarray = np.array([2,71,0,34])
print(my_ndarray)

[ 2 71  0 34]


In [22]:
my_ndarray.nonzero()

(array([0, 1, 3], dtype=int64),)

In [23]:
my_ndarray[[0, 1, 3]]

array([ 2, 71, 34])

In [24]:
my_ndarray[my_ndarray.nonzero()]

array([ 2, 71, 34])

In [25]:
np.amax(my_ndarray)

71

In [27]:
[0.98, 0.02]

[0.98, 0.02]

In [28]:
my_ndarray = np.array([2,71,0,34])
print(my_ndarray)
print(my_ndarray.argmax())    # índice del valor más alto
print(my_ndarray.argmin())    # índice del valor más bajo
print(my_ndarray.nonzero())   # retorna los índices de los elementos distintos a 0

[ 2 71  0 34]
1
2
(array([0, 1, 3], dtype=int64),)


In [29]:
nueva = np.array([[2,71,0,34], [2,171,-35,34]])
print(nueva.argmax())
print(np.amax(nueva))

5
171


In [30]:
nueva.ndim

2

In [31]:
nueva[1][1]

171

In [10]:
my_ndarray.ndim

NameError: name 'my_ndarray' is not defined

In [11]:
my_ndarray = np.full((2,5),-3) # matrix 5x2
print(my_ndarray)
print(my_ndarray.size)        # número de elementos
print(my_ndarray.shape)       # dimensiones
print(my_ndarray.ndim)        # número de dimensiones

[[-3 -3 -3 -3 -3]
 [-3 -3 -3 -3 -3]]
10
(2, 5)
2


#### Redimensionar los datos

In [12]:
my_ndarray = np.array([[10, 71, 21, 19, 213, 412, 111, 98]])  # matrix 1x8
print(my_ndarray.shape)
print(my_ndarray.ndim)
print(my_ndarray)
print(my_ndarray.size)


(1, 8)
2
[[ 10  71  21  19 213 412 111  98]]
8


In [13]:
new_dims = my_ndarray.reshape(4, 2)
print(new_dims)

[[ 10  71]
 [ 21  19]
 [213 412]
 [111  98]]


In [16]:
x = np.array([100, 10, 1]).reshape(3,1)
x.shape

(3, 1)

In [17]:
x

array([[100],
       [ 10],
       [  1]])

In [19]:
my_ndarray = np.array([[10, 71, 21, 19, 213, 412, 111, 98]])  # matrix 1x8
print(my_ndarray.shape)
print(my_ndarray)

# cambiar las dimensiones a 4x2
new_dims = my_ndarray.reshape(4, 2)
print(new_dims)

# cambiar las dimensiones a 2x4
new_dims = my_ndarray.reshape(2, 4) # qué sucede si utilizamos otros valores?
print(new_dims)

(1, 8)
[[ 10  71  21  19 213 412 111  98]]
[[ 10  71]
 [ 21  19]
 [213 412]
 [111  98]]
[[ 10  71  21  19]
 [213 412 111  98]]


In [18]:
# Cambiar ejes
new_dims = np.arange(16).reshape(4,4)
print(new_dims)
print(new_dims.swapaxes(0,1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [20]:
# reducir a 1D
new_dims = np.arange(9).reshape(3,3)
print(new_dims)
print(np.arange(9))
print(new_dims.flatten())
print(type(new_dims.flatten()))
print(new_dims.reshape(1,9))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>
[[0 1 2 3 4 5 6 7 8]]


In [21]:
new_dims.reshape(1,9)[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
new_dims.flatten()[0]

0

In [23]:
# reducir a 1D
new_dims = np.arange(16).reshape(4,4)
print(new_dims)
print(new_dims.reshape(1, -1))
print(new_dims.flatten())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [24]:
type(new_dims.reshape(1, -1))

numpy.ndarray

In [25]:
new_dims.reshape(1, -1)[0][0]

0

In [ ]:
type(new_dims.flatten())

In [26]:
new_dims.flatten()[0]

0

## Manipulación de ndarrays

In [27]:
# ordenar
array1 = np.array([10,2,9,17])
array2 = array1.copy()
array1.sort()
print(array1)

[ 2  9 10 17]


In [28]:
array2 = -np.sort(-array2)

In [29]:
array2

array([17, 10,  9,  2])

In [30]:
np.flip(array1)

array([17, 10,  9,  2])

In [31]:
shopping_list = [ ['onions','carrots','celery'], ['apples','oranges','grapes'] ] # 2D
array = np.array(shopping_list)
array

array([['onions', 'carrots', 'celery'],
       ['apples', 'oranges', 'grapes']], dtype='<U7')

In [32]:
array.sort()
array

array([['carrots', 'celery', 'onions'],
       ['apples', 'grapes', 'oranges']], dtype='<U7')

In [33]:
np.flip(array)

array([['oranges', 'grapes', 'apples'],
       ['onions', 'celery', 'carrots']], dtype='<U7')

In [34]:
# Juntar dos arrays
a1 = [0,0,0,0,0,0]
a2 = [1,1,1,1,1,1]
print(np.hstack((a1,a2))) # una al lado de la otra
print(np.vstack((a1,a2))) # una encima de la otra

print(np.hstack((a1,a2)).shape)
print(np.vstack((a1,a2)).shape)

[0 0 0 0 0 0 1 1 1 1 1 1]
[[0 0 0 0 0 0]
 [1 1 1 1 1 1]]
(12,)
(2, 6)


In [35]:
# dividir un array
array = np.arange(16).reshape(4,4)
print(array)
print(np.array_split(array,2)) # divide array en 2 partes iguales
print(np.array_split(array,3)) # divide array en 3 partes "iguales"

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [36]:
# dividir un array
array = np.arange(16).reshape(4,4)
print(array)
print(np.array_split(array,[1,2,3], axis = 0)) # divide array, por la fila 3

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [37]:
array = np.arange(64).reshape(8,8)
print(array)
print(np.array_split(array, [1, 3], axis = 0))  # divide array por la fila 1 y 2

print(np.array_split(array, [1, 3], axis = 1))  # divide array por la columna 1 y 2
# axis = n_dimensions - 1

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]
[array([[0, 1, 2, 3, 4, 5, 6, 7]]), array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])]
[array([[ 0],
       [ 8],
       [16],
       [24],
       [32],
       [40],
       [48],
       [56]]), array([[ 1,  2],
       [ 9, 10],
       [17, 18],
       [25, 26],
       [33, 34],
       [41, 42],
       [49, 50],
       [57, 58]]), array([[ 3,  4,  5,  6,  7],
       [11, 12, 13, 14, 15],
       [19, 20, 21, 22, 23],
       [27, 28, 29, 30, 31],
       [35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47],
       [51, 52, 53, 54, 55],
       [

In [38]:
cosa2 = np.array_split(array, [1, 3], axis = 1)

print(cosa2[2][6])

[51 52 53 54 55]


# Índices y slicing
- De manera análoga a índices y slicing para listas

In [39]:
array = np.arange(10, 16)
print(array)
print(array[2])    # acceso unidimensional
print(array[:-1])  # slice

[10 11 12 13 14 15]
12
[10 11 12 13 14]


In [40]:
# bidimensional
array = np.arange(16).reshape(4,4)
print(array)
print(array[2, 2]) # fila, columna

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
10


In [41]:
# multidimensional
array = np.arange(36).reshape(2,3,6)
print(array)
print(array[1,2,4])

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]
34


In [45]:
lista = [[[ 0 ,1,  2,  3,  4,  5],
  [ 6,  7,  8,  9, 10, 11],
  [12, 13, 14, 15, 16, 17]],

 [[18, 19, 20, 21, 22, 23],
  [24, 25, 26, 27, 28, 29],
  [30, 31, 32, 33, 34, 35]]]

In [42]:
array[1,2,4] = 75

In [43]:
array

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 75, 35]]])

In [46]:
lista[1][2][4]

34

In [47]:
array

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 75, 35]]])

#### NumPy es row major

In [48]:
row_major = np.array([1, 2, 3, 4, 5, 6])
row_major = row_major.reshape(2,3)
print(row_major)

[[1 2 3]
 [4 5 6]]


In [49]:
row_major = np.array([1, 2, 3, 4, 5, 6])
row_major = row_major.reshape(2,3, order='F')  # col major
print(row_major)

[[1 3 5]
 [2 4 6]]


In [50]:
row_major = np.array([1, 2, 3, 4, 5, 6])
row_major = row_major.reshape(2,3, order='C')  # by default, row major
print(row_major)

[[1 2 3]
 [4 5 6]]


In [51]:
row_major = np.array([1, 2, 3, 4, 5, 6])
row_major = row_major.reshape(2,3,order='C')  # by default, row major
print(row_major)

col_major = np.array([1, 2, 3, 4, 5, 6])
col_major = col_major.reshape(2,3,order='F')  # col major
print(col_major)

[[1 2 3]
 [4 5 6]]
[[1 3 5]
 [2 4 6]]


#### Slice

In [52]:
# se puede hacer slice por fila o columna
array = np.arange(81).reshape(9,9)
print(array)
print(array[5:,5])

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]
[50 59 68 77]


In [53]:
# se puede hacer slice por fila o columna
array = np.arange(9).reshape(3,3)
print(array)
print(array[0:2,1:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2]
 [4 5]]


#### Diferencias entre índices y slicing en listas y ndarrays:
- ¡Retornan una referencia, no una copia!

In [54]:
# uso de slice en listas, retorna copia
lista = [0,1,2,3,4,5,6,7,8,9]
my_copy = lista[0:2]  # devuelve una copia
print(my_copy)
my_copy[0] = 222
print(lista)
print(my_copy)

[0, 1]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[222, 1]


In [55]:
# slicing retorna una referencia en ndarrays
array = np.arange(10)
my_copy = array[2:5]  # devuelve una referencia
print(array)
print(my_copy)
my_copy[0] = 222
print(array)
print(my_copy)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[  0   1 222   3   4   5   6   7   8   9]
[222   3   4]


In [56]:
# copiar ndarrays
array = np.arange(10)
my_copy = array[2:5].copy()  # hay que hacer la copia explicitamente
my_copy[0] = 222
print(array)
print(my_copy)

[0 1 2 3 4 5 6 7 8 9]
[222   3   4]


In [57]:
array = np.arange(9).reshape(3,3)

print(array)

array2 = array[:,0].reshape(3,1)

print(array2)

print(array2.shape)

print(array.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0]
 [3]
 [6]]
(3, 1)
(3, 3)


- Permite asignar valores a un corte

In [58]:
array = np.arange(10)
print(array)
array[0:3] = -1
print(array)

[0 1 2 3 4 5 6 7 8 9]
[-1 -1 -1  3  4  5  6  7  8  9]


- Slicing condicionales (mask)

In [59]:
array = np.arange(-3,4)
print(array)

[-3 -2 -1  0  1  2  3]


In [60]:
# slicing condicional
array = np.arange(-3,4)
print(array)

mask = array < 0
print(mask)

print(array[mask])

array[mask] = 0
print(array)

[-3 -2 -1  0  1  2  3]
[ True  True  True False False False False]
[-3 -2 -1]
[0 0 0 0 1 2 3]


In [61]:
np.arange(-3,4)

array([-3, -2, -1,  0,  1,  2,  3])

In [62]:
# slicing condicional
array = np.arange(-3,4)
print(array)
mask = array % 2 == 0
print(mask)

array_par = array[mask]  # devuelve una copia
print(array_par)

array_par[0] = -10
print(array)
print(array_par)

[-3 -2 -1  0  1  2  3]
[False  True False  True False  True False]
[-2  0  2]
[-3 -2 -1  0  1  2  3]
[-10   0   2]


In [63]:
# slicing condicional
array = np.arange(-3,4)
mask = array % 2 == 0
print(mask)
print(array)
print(array[mask])

array[mask] = 10 # ??
print(array)

mask = array == 10
print(mask)
array[mask] = 0 # ??
print(array)

[False  True False  True False  True False]
[-3 -2 -1  0  1  2  3]
[-2  0  2]
[-3 10 -1 10  1 10  3]
[False  True False  True False  True False]
[-3  0 -1  0  1  0  3]


- Acceso a múltiples valores con listados de índices

In [64]:
array = np.arange(-10,0)
print(array)
print(array[[2,3,1]])

ar = array[[2,3,1]]
print(ar)
ar[0] = 999
print(ar)
print(array)

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1]
[-8 -7 -9]
[-8 -7 -9]
[999  -7  -9]
[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1]


# Funciones matemáticas
- Aplicar operaciones entre escalares y arrays o entre arrays

In [70]:
# listas y escalares
lista = [0,1,2,3]
lista *= 3
print(lista)
lista = lista + [1]
print(lista)

[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]
[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 1]


In [66]:
# ndarray hace las operaciones sobre los elementos
array = np.ones(4) * 2
print(array)
array += 10
print(array)

[2. 2. 2. 2.]
[12. 12. 12. 12.]


In [71]:
# operaciones entre arrays es como operaciones entre matrices
array_1 = np.ones(4) * 2
array_2 = np.arange(4) + 1

print(array_1)
print(array_2)

print(array_1 + array_2)
print(array_1 - array_2)
print(array_1 * array_2)
print(array_1 / array_2)

[2. 2. 2. 2.]
[1 2 3 4]
[3. 4. 5. 6.]
[ 1.  0. -1. -2.]
[2. 4. 6. 8.]
[2.         1.         0.66666667 0.5       ]


In [ ]:
[0, 0, 1,2,3,4]

[2,4,6,8,9,8]

Si las arrays no tienen las mismas dimensiones --> [broadcasting](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html)
- Restricciones

## Operadores unarios y binarios

| Tipo | Operación | Descripción |
|:---------|:-----|:-----|
| Unario | *abs* | Valor absoluto de cada elemento |
| | *sqrt* | Raíz cuadrada de cada elemento |
| | *exp* | e^x, siendo x cad elemento |
| | *log, log10, log2* | Logaritmos en distintas bases de cada elemento |
| | *sign* | Retorna el signo de cada elemento (-1 para negativo, 0 o 1 para positivo) |
| | *ceil* | Redondea cada elemento por arriba |
| | *floor* | Redondea cada elemento por abajo |
| | *isnan* | Retorna si cada elemento es Nan |
| | *cos, sin, tan* | Operaciones trigonométricas en cada elemento |
| | *arccos, arcsin, arctan* | Inversas de operaciones trigonométricas en cada elemento |
| Binario | *add* | Suma de dos arrays |
| | *substract* | Resta de dos arrays |
| | *multiply* | Multiplicación de dos arrays |
| | *divide* | División de dos arrays |
| | *maximum, minimum* | Retorna el valor máximo/mínimo de cada pareja de elementos |
| | *equal, not_equal* | Retorna la comparación (igual o no igual) de cada pareja de elementos |
| | *greater, greater_equal, less, less_equal* | Retorna la comparación (>, >=, <, <= respectivamente) de cada pareja de elementos |

In [72]:
# ejemplos de operadores
array = np.arange(5)
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [75]:
# ejemplos de operadores
array1 = np.arange(4)
print(array1)
array2 = np.array([0,-1,2,-3])
print(array2)
print(np.greater(array1,array2))

print(np.less(array1, array2))

[0 1 2 3]
[ 0 -1  2 -3]
[False  True False  True]
[False False False False]


# Estadística descriptiva
- Importante saber la naturaleza de los datos
- Valores máximos, mínimos, distribución, etc.

| Función | Descripción |
|:---------|:-----|
| *sum(arr)* | Suma de todos los elementos de *arr* |
| *mean(arr)* | Media aritmética de los elementos de *arr* |
| *std(arr)* | Desviación estándar de los elementos de *arr* |
| *cumsum(arr)* | Devuelve array con la suma acumulada de cada elementos con todos los anteriores |
| *cumprod(arr)* | Devuelve array con el producto acumulado de cada elementos con todos los anteriores |
| *min(arr), max(arr)* | Mínimo y máximo de *arr* |
| *any(arr)* | En array de tipo *bool*, retorna *True* si algún elemento es *True* |
| *all(arr)* | En array de tipo *bool*, retorna *True* si todos los elementos son *True* (o >0 en valores numéricos) |
| *unique(arr)* | Devuelve un array con valores únicos |
| *in1d(arr1, arr2)* | Devuelve un array con bool indicando si cada elemento de *arr1* está en *arr2* |
| *union1d(arr1, arr2)* | Devuelve la unión de ambos arrays |
| *intersect1d(arr1, arr2)* | Devuelve la intersección de ambos arrays |

In [76]:
# sum != cumsum
array1 = np.arange(9)
print(array1)
print(array1.sum())
print(array1.cumsum())

[0 1 2 3 4 5 6 7 8]
36
[ 0  1  3  6 10 15 21 28 36]


In [77]:
# any vs all
array1 = np.arange(10).reshape(2,5)
print(array1)
print(array1.any()) # any para saber si hay elementos True o valores > 0
print(array1.all()) # all para saber si TODOS los elementos son True o valores > 0

[[0 1 2 3 4]
 [5 6 7 8 9]]
True
False


In [78]:
array1 = np.ones(10).reshape(2,5)
print(array1)
print(array1.any())
print(array1.all())

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
True
True


In [79]:
# todas las funciones aceptan parametro 'axis' 
# 0 para columnas, 1 para filas, 2 para profundidad...
array1 = np.arange(10).reshape(5,2)
print(array1)
print(array1.all(axis=0))
print(array1.all(axis=1))
print(array1.all())

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[False  True]
[False  True  True  True  True]
False


# Álgebra lineal
- numpy.linalg contiene funciones para álgebra lineal
- dot product, multipliacción de matrices, cálculo del determinante, factorizaciones...


| Función | Descripción |
|:---------|:-----|
| *dot(mat1, mat2)* | Devuelve el producto escalar entre dos arrays. Si son matrices 2D, es equivalente a la multiplicación de ambas |
| *matmul(mat1, mat2)* | Devuelve el producto entre dos matrices |
| *trace(mat1, mat2)* | Suma de las diagonales de ambas matrices |
| *det(mat)* | Devuelve el determinante de la matriz |
| *eig(mat)* | Computa los autovalores y autovectores de la matriz cuadrada *mat* |
| *inv(mat)* | Devuelve la inversa de la matriz |
| *qr(mat)* | Computa la factorización QR de *mat* |
| *solve(A, b)* | Resuelve el sistema lineal de ecuaciones *Ax = b* para *b*, cuando *A* es una matriz cuadrada |

In [80]:
A = np.arange(12).reshape(4,3)
B = np.arange(9).reshape(3,3)

print(A)
print(B)

print(np.matmul(A,B))
print(np.dot(A, B))
print(A @ B)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]
 [ 96 126 156]]
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]
 [ 96 126 156]]
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]
 [ 96 126 156]]


In [81]:
import numpy.linalg as linalg

# resolver sistema de ecuaciones
# 3x + 2y + 5z = 12
# x - 3y -z = 2
# 2x -y +12z = 32
# Ax = b --> resolver para x

a = np.array([ [3,2,5],[1,-3,-1],[2,-1,12] ])
b  = np.array([12,2,32])

print(a)
print(b)
x, y, z = linalg.solve(a,b)
print('x=' + str(x) + ', y=' + str(y), 'z= ', str(z))

[[ 3  2  5]
 [ 1 -3 -1]
 [ 2 -1 12]]
[12  2 32]
x=0.7543859649122807, y=-1.2280701754385965 z=  2.43859649122807


In [85]:
#matriz identidad
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Filtrado de datos
- Filtrar y modificar datos numéricos con np.where
- Retorna A o B en función de una condición en una array

In [2]:
prices = np.array([0.99, 14.49, 19.99, 20.99, 0.49])
print(prices)

[ 0.99 14.49 19.99 20.99  0.49]


In [3]:
mask = []
for i in range(len(prices)):
    if prices[i] < 1:
        mask.append(True)
    else:
        mask.append(False)
        

In [4]:

# mask con los elementos menores de 1
mask = np.where(prices < 1, True, False)
print(mask)
print(prices[mask])

print(np.where(prices < 1, 1.0, prices))

[ True False False False  True]
[0.99 0.49]
[ 1.   14.49 19.99 20.99  1.  ]


In [89]:
# Se puede usar para sustituir datos fuera de rango
bank_transfers_values = np.array([0.99, -1.49, 19.99, 20.99, -0.49, 12.1]).reshape(2, 3)
print(bank_transfers_values)
clean_data = np.where(bank_transfers_values > 0, bank_transfers_values, 0)
print(clean_data)

[[ 0.99 -1.49 19.99]
 [20.99 -0.49 12.1 ]]
[[ 0.99  0.   19.99]
 [20.99  0.   12.1 ]]


In [90]:
# limpiar NaN (sustitución)
data = [10, 12, -143, np.nan, 1, -3] # np.nan --> NotANumber, elemento especial
print(data)
data_clean = np.where(np.isnan(data),0, data)
print(data_clean)

[10, 12, -143, nan, 1, -3]
[  10.   12. -143.    0.    1.   -3.]


In [91]:
np.isnan(data)

array([False, False, False,  True, False, False])

In [92]:
# np.where puede seleccionar elementos
bank_transfers_values = np.array([0.99, -1.49, 19.99, 20.99, -0.49, 12.1]).reshape(2, 3)
credits = np.where(bank_transfers_values > 0) # array de índices para los que la condición es True

print(bank_transfers_values)

print(credits)
print(bank_transfers_values[credits]) # es igual que bank_transfers_values[bank_transfers_values > 0]

[[ 0.99 -1.49 19.99]
 [20.99 -0.49 12.1 ]]
(array([0, 0, 1, 1], dtype=int64), array([0, 2, 0, 2], dtype=int64))
[ 0.99 19.99 20.99 12.1 ]


In [93]:
# valor de array dependiendo del valor en array referencia
rewards_default = np.arange(6)
print(rewards_default)
rewards_upgrade = np.arange(6) * 10
print(rewards_upgrade)
daily_points = np.array([0, 0, 1, 6, 0, 2])
print(daily_points)

final_rewards = np.where(daily_points > 1, rewards_upgrade, rewards_default)
print(final_rewards)

[0 1 2 3 4 5]
[ 0 10 20 30 40 50]
[0 0 1 6 0 2]
[ 0  1  2 30  4 50]


# Números aleatorios
- Python módulo random

In [94]:
import random
print(random.random()) # número entre 0 y 1
print(random.randint(0,5)) # entero entre dos valores
print(random.uniform(0,5)) # real entre dos valores

0.023358016335918497
4
3.625604406700193


In [96]:
# elegir un elemento al azar dentro de una colección
names = ['Marta','Anna','Vanesa']
random.choice(names)
print(f"Mi mejor amiga es: {random.choice(names)}")

Mi mejor amiga es: Anna


## NumPy.random
- Generar fácilmente listas con valores aleatorios

In [99]:
print(np.random.rand()) # número entre 0 y 1
print(np.random.randint(0,5)) # entero entre dos valores 
print(np.random.randint(5, size=(2, 4))) # parametro 'size' para indicar las dimensiones)

0.7956127607434924
3
[[2 3 4 2]
 [2 2 0 4]]


In [100]:
elemento = np.zeros((2,4))

print(elemento)

for i in range(0,2):
    for j in range(0,4):
        elemento[i, j] = np.random.randint(0,5)

elemento

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[0., 3., 1., 0.],
       [2., 4., 4., 4.]])

In [101]:
# array de elementos aleatorios (distribucion normal gaussiana, media 0, desviación 1)
print(np.random.randn(4,2))

[[ 0.89243269  0.51505107]
 [ 0.48341022  1.36225558]
 [ 2.32105266 -0.28077453]
 [ 1.2139879   2.58693822]]


In [102]:
# otras distribuciones
print(np.random.binomial(n=5, p=0.3)) # 'n' intentos, 'p' probabilidad
print(np.random.uniform(low=0, high=10)) # distribución uniforme
print(np.random.poisson(lam=2, size=(2,2))) # 'lam' número de ocurrencias esperadas, retornar 'size' valores

2
2.8700400142346947
[[2 1]
 [2 0]]


## Random seed
- Números pseudo-aleatorios
- Ordenadores generan números a partir de ecuaciones
- Basadas en un número inicial (seed)
- Bueno para reproducibilidad de experimentos

In [103]:
i = 5
for _ in range(5):
    print(i)
    np.random.seed(i) # misma semilla
    print(np.random.rand())
    print(np.random.rand())
    print(np.random.rand())

print()    
    
for i in range(8):
    print(i)
    np.random.seed(i) # diferentes semillas
    print(np.random.rand())

5
0.22199317108973948
0.8707323061773764
0.20671915533942642
5
0.22199317108973948
0.8707323061773764
0.20671915533942642
5
0.22199317108973948
0.8707323061773764
0.20671915533942642
5
0.22199317108973948
0.8707323061773764
0.20671915533942642
5
0.22199317108973948
0.8707323061773764
0.20671915533942642

0
0.5488135039273248
1
0.417022004702574
2
0.43599490214200376
3
0.5507979025745755
4
0.9670298390136767
5
0.22199317108973948
6
0.8928601514360016
7
0.07630828937395717


# Escritura y lectura de ndarrays a archivos 
- Para futuro acceso
- Compartir datos con otros
- Formato *.npy

In [104]:
# escribir a archivo
import os
ruta = os.path.join("res" ,"o_values_array.npy")
values = np.random.randint(9, size=(3,3))
np.save(ruta, values)
print(values)

[[6 3 3]
 [7 7 7]
 [8 8 7]]


In [ ]:
ruta2 = 'res' + '/' + 'nombre.nmp'

In [105]:
ruta

'res\\o_values_array.npy'

In [106]:
# leer de archivo
old_values = np.load(ruta)
print(old_values)

[[6 3 3]
 [7 7 7]
 [8 8 7]]


In [107]:
# escribir y cargar múltiples arrays
ruta = os.path.join("res" ,"o_array_group.npz")
values1 = np.random.randint(9,size=(3,3))
values2 = np.random.randint(4,size=(2,2))
values3 = np.random.randint(16,size=(4,4))
np.savez(ruta,values1,values2,values3) # añade la extensión .npz   

In [108]:
print(values3)

[[ 0 11 13  0]
 [ 2  8  9 14]
 [ 6  4 14  9]
 [ 7  3  3  8]]


In [109]:
print(values3)

[[ 0 11 13  0]
 [ 2  8  9 14]
 [ 6  4 14  9]
 [ 7  3  3  8]]


In [110]:
# leer los archivos (retorna un diccionario con las arrays)
npzfile = np.load(ruta)
print(type(npzfile.files))


<class 'list'>


In [111]:
my_dict = {}
my_dict['a'] = np.random.randint(9,size=(3,3))
my_dict['b'] = 7
my_dict['c'] = 4

In [112]:
for key in my_dict.keys():
    print(my_dict[key])

[[3 0 1]
 [0 0 6]
 [7 7 3]]
7
4


In [113]:
npzfile.files

['arr_0', 'arr_1', 'arr_2']

In [114]:
for key in npzfile.files: # array.files contiene el nombre de las arrays (arr_0, arr_1...)
    print(npzfile[key])

[[6 4 0]
 [7 0 7]
 [6 3 5]]
[[0 0]
 [3 1]]
[[ 0 11 13  0]
 [ 2  8  9 14]
 [ 6  4 14  9]
 [ 7  3  3  8]]


In [ ]:
values3

In [ ]:
npzfile['arr_2']

### ¿Por qué molestarse con .npy?
- Bases de datos suelen estar en CSV o txt, que requieren lectura con streams (parsing)
- ¿Para qué escribir los datos de nuevo?

In [ ]:
ruta_csv = os.path.join("res" ,"fdata.csv")
with open(ruta_csv,'r') as f:
    data_str = f.read()
data = data_str.split(',')
data_array = np.array(data, dtype = np.int8).reshape(1000,1000)
print(data_array)

ruta_npy = os.path.join("res" ,"o_fdata.npy")
np.save(ruta_npy, data_array)

In [ ]:
%%timeit # magic function jupyter
with open(ruta_csv,'r') as f:
    data_str = f.read()
data = data_str.split(',')
data_array = np.array(data,  dtype = np.int8).reshape(1000,1000)

In [ ]:
%%timeit
data = np.load(ruta_npy)

### velocidad + simplicidad vs memoria